### ISSUE TITLE
Reading example .bpmn files in modeler/viewer

### ISSUE THREAD

**Issue by aars** [e2ebridge/bpmn#18]
Are the provided example bpmn files supposed to be viewable in any BPMN2.0 compatible modeler/viewer? I'm having trouble opening them.

bpmn.io gives no errors but draws no diagram.
camundaModeler gives a bunch of errors and draws no diagram.
Errors examples (on opening `collaboration.bpmn`):
`feature 'label' not found`
`feature 'mxCell' not found`
`BPMNPlane not associated with collaboration`
`Element *N*: Diagram element not found, element will not be shown`

Then there's yaoqiang, which does display a diagram, but warns that the xml is malformed and should be fixed.

What viewer/modeler can I use to open the example files?

Should I expect issues when creating new bpmn files with one of these modelers? (I'm planning on using bpmn-js/bpmn.io)

**Comment by cyrilschmitt** [comment]
The examples bpmn are made with our own editor and you won't be able to open them in another.

The bpmn engine only uses the model part of bpmn 2.0 (namespace: http://www.omg.org/spec/BPMN/20100524/MODEL). All editors that follow this will generate compatible models.

For the test models we also used yaoqiang.

**Comment by aars** [comment]
Thanks.

**Comment by Dmitry-N-Medvedev** [comment]
@cyrilschmitt , so you are using your own editor, right? will you share it somehow to the public, for neither yaoqiang, nor camunda are able to open them.

**Comment by cyrilschmitt** [comment]
We don't plane to open the editor. We only made a prototype there is no scheldule for next steps.

As said previously you can use any BPMN editor to create compatible BPMN.
