### ISSUE TITLE
raising error events in your script

### ISSUE THREAD

**Issue by TomKaltz** [e2ebridge/bpmn#37]
I see that you can specify a global unhandled exception handler callback per process in your js file. If I model script exceptions as an intermediate error event in my bpmn file, is there a way to raise those events when the script error occurs?  Would I use a try/catch and trigger the event manually?  If so, how?

I am new to BPMN so hopefully I missed something in the docs.

**Comment by TomKaltz** [comment]
Ok so I have found ```triggerEvent(eventName, data)``` in the README.  Is something like the following acceptable in a script task?

```
try {
  //an operation that might fail
} catch (e) {
  this.triggerEvent(errorBoundaryEventName, {error:e})
}
```

**Comment by cyrilschmitt** [comment]
This is acceptable but keep in mind that this doesn't stop the script. That means all what you have after the try/catch will still be executed.
